version: '3.5'

services:

  postgres:
    container_name: postgressql
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - clean

  cassandra:
    container_name: cassandra
    image: cassandra:4.0.6
    ports:
      - 9042:9042
    volumes:
      - cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=citizix
    networks:
      - clean

  mongodb:
    container_name: mongodb
    image: mongo:6.0.2
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=clean
      - MONGO_INITDB_ROOT_USERNAME=clean
      - MONGO_INITDB_ROOT_PASSWORD=clean
    networks:
      - clean


networks:
  clean:

volumes:
    postgres:
    cassandra:
    mongodb: