CREATE ROLE clean NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'clean';
CREATE DATABASE clean WITH OWNER =  clean;
CREATE ROLE keycloak NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'keycloak';
CREATE DATABASE keycloak WITH OWNER =  keycloak;